### ISSUE TITLE
Fix for running on x64

### ISSUE THREAD

**Issue by genejo** [secile/UsbCamera#1]
Thanks for the neat library!

Tried running after compiling for x64 and it broke. Found a fix - you may want to replace line 320:
```
var dst = new IntPtr(bmp_data.Scan0.ToInt32() + (stride * y));
```
with
```
var dst = IntPtr.Add(bmp_data.Scan0, stride * y);
```
to [avoid manually interfering with pointer arithmetics](https://stackoverflow.com/questions/12390035/intptr-toint32-and-x64-systems).

**Comment by secile** [comment]
Thank you for your information.
In my PC, your problem is not occur, but I understand what you say.
Under x64, IntPtr value can be larger than 4byte,
therefore Scan0.ToInt32() can be cause overflow exception.

I'll fix this problem future release. Thank you.
