### ISSUE TITLE
On Capture Callback

### ISSUE THREAD

**Issue by EugeneQilo** [secile/UsbCamera#16]
Hello @secile,
What you have here is gold. Thank you for putting it together.

Is it possible to pass a callback function on capture? This is essential for cameras which have an external capture button. We need to have a way to detect it and either manually trigger a GetBitmap or the event will take one and pass it to the callback function.

**Comment by secile** [comment]
Hello, EugeneQilo.
Thank you! I'm very happy to hear such a word.

I currently have no idea how to support capture button,
Please give me some time to research.

Basically, I want to support capture button if possible.

**Comment by secile** [comment]
This is developing version. could you test the code and please let me know it works fine or not. I uploaded UsbCamera.cs compressed with zip.

[UsbCamera.zip](https://github.com/secile/UsbCamera/files/9729107/UsbCamera.zip)

**Comment by secile** [comment]
Hello.
Does developing version works fine?
could you test it and please let me know it works fine or not.
