### ISSUE TITLE
missing events

### ISSUE THREAD

**Issue by hellottyp** [secile/UsbCamera#21]
```
           
// create instance.
camera = new UsbCamera(cameraIndex, format);

// show preview on control. (works light.)
camera.SetPreviewControl(this.panVideo.Handle, this.panVideo.ClientSize);

private void panVideo_MouseMove(object sender, MouseEventArgs e)
 {
       //it never fired over the camera region.but fired over other whitespace region.
       Console.WriteLine("mouse move");
}
```

**Comment by secile** [comment]
Hello, thank you for your information.

This is library's problem.
I'll fix future release, but could you add 1 line (see below) and try again?

```cs
// about line 260.
builder.RenderStream(ref pinCategory, ref mediaType, vcap_source, null, null);
vw.put_Owner(controlHandle);
vw.put_MessageDrain(controlHandle);   <- ADD THIS LINE.
```

**Comment by hellottyp** [comment]
panel1.MouseMove += (s, ev) =>
                    {
                        Console.WriteLine("mouse move"); // work well
                    };

                    panel1.MouseLeave += (s, ev) =>
                    {
                        Console.WriteLine("mouse leave"); //fired too
                    };

                    panel1.MouseClick += (s, ev) =>
                    {
                        Console.WriteLine("mouse click"); //not work
                    };

**Comment by hellottyp** [comment]
I have a none border window.I want to drag the window by the container of the camera.

**Comment by secile** [comment]
It seems that it is limitation of DirectShow.
Please use MouseUp and MouseDown event instead.
