### ISSUE TITLE
Capture Pin not working on all cameras

### ISSUE THREAD

**Issue by EugeneQilo** [secile/UsbCamera#33]
Hello @secile,
We deployed the latest version, and we have this observation. The Still Pin works on some Cameras but it doesn't on some other cameras. To be accurate, it was tested on 3 cameras, only 1 worked.

Could there be anything missed in the code? We have access to one of the cameras that didn't work, so if there is anything to check to troubleshoot this issue we will be happy to do.

**Comment by secile** [comment]
Thank you for your information.

Could you check camera.StillImageAvailable flag? If flag is false, the camera is not support still image capture.
Not all camera supports still imagecapture.

**Comment by secile** [comment]
about line 276, does variable sample is null?

```cs
var sample = ConnectSampleGrabberAndRenderer(graph, builder, vcap_source, DirectShow.DsGuid.PIN_CATEGORY_STILL);
```

if sample is not null, about line 283,
does variable video_con is null?

```cs
var video_con = vcap_source as DirectShow.IAMVideoControl;
```

**Comment by secile** [comment]
I closed this issue because no response.
