### ISSUE TITLE
Would it recognize my DSLR camera via USB port on Windows 10?

### ISSUE THREAD

**Issue by aks84** [secile/UsbCamera#4]
Hello, 
I don't know if I am asking right question..
 
But for last few days, I have been looking for a way to write a device driver that can recognize connected cameras on computer/laptops via USB port, as a video input source on streaming software like OSB. 

I just want to know how your code works and if there is a way to create such device driver?

Thanks in Advance..

**Comment by secile** [comment]
Hello.
I'm not a device driver expert. so I can not tell you how to write device driver.
But I can tell you how my code works.

My code handles usb camera via DirectShow. DirectShow is a multimedia framework and API produced by Microsoft. If your camera recognized as DirectShow device by windows, my code supports your camera. If your camera can be used with Skype, your camera is DirectShow.

Did your question get resolved? If you still have questions, please ask again.
